apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sbdpfuo84-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbdpfuo84-go 
  name: sbdpfuo84-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sbdpfuo84-go 
